=== hnomkeng/AionEncomBase_Java8/AL-Game/data/static_data/quest_script_data/quest_script_data.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../quest_data/quest_data.xsd"/>
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="quest_scripts" type="QuestScripts"/>
	<xs:complexType name="QuestScripts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item_collecting" type="ItemCollectingData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="report_to" type="ReportToData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="monster_hunt" type="MonsterHuntData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mentor_monster_hunt" type="MentorMonsterHuntData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="work_order" type="WorkOrdersData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="report_to_many" type="ReportToManyData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="relic_rewards" type="RelicRewardsData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="crafting_rewards" type="CraftingRewardsData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="xml_quest" type="XmlQuestData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="kill_in_world" type="KillInWorldData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="skill_use" type="SkillUseData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="kill_spawned" type="KillSpawnedData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item_order" type="ItemOrdersData" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="fountain_rewards" type="FountainRewardsData" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QuestScriptData" abstract="true">
		<xs:attribute name="id" type="xs:int" use="required"/>
		<xs:attribute name="movie" type="xs:int" use="optional"/>
		<xs:attribute name="mission" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="XmlQuestData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="on_talk_event" type="OnTalkEvent" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="on_kill_event" type="OnKillEvent" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int"/>
				<xs:attribute name="end_npc_id" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QuestCondition" abstract="true">
		<xs:attribute name="op" type="ConditionOperation" use="required"/>
	</xs:complexType>
	<xs:complexType name="QuestOperation" abstract="true"/>
	<xs:complexType name="QuestEvent" abstract="true">
		<xs:sequence>
			<xs:element name="conditions" type="QuestConditions" minOccurs="0" maxOccurs="1"/>
			<xs:element name="operations" type="QuestOperations" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="ids" type="NumberListType"/>
	</xs:complexType>
	<xs:complexType name="QuestNpc">
		<xs:sequence>
			<xs:element name="dialog" type="QuestDialog" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="QuestVar">
		<xs:sequence>
			<xs:element name="npc" type="QuestNpc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="value" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="QuestDialog">
		<xs:sequence>
			<xs:element name="conditions" type="QuestConditions" minOccurs="0" maxOccurs="1"/>
			<xs:element name="operations" type="QuestOperations" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="OnTalkEvent">
		<xs:complexContent>
			<xs:extension base="QuestEvent">
				<xs:sequence>
					<xs:element name="var" type="QuestVar" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="OnKillEvent">
		<xs:complexContent>
			<xs:extension base="QuestEvent">
				<xs:sequence>
					<xs:element name="monster" type="Monster" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="complite" type="QuestOperations" minOccurs="0" maxOccurs="1"/>
					</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QuestConditions">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="dialog_id" type="DialogIdCondition" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="npc_id" type="NpcIdCondition" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="pc_inventory" type="PcInventoryCondition" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="quest_status" type="QuestStatusCondition" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="quest_var" type="QuestVarCondition" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="operate" type="ConditionUnionType" use="required"/>
	</xs:complexType>
	<xs:complexType name="QuestOperations">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="give_item" type="GiveItemOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="set_quest_var" type="SetQuestVarOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="npc_dialog" type="NpcDialogOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="set_quest_status" type="SetQuestStatusOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="start_quest" type="StartQuestOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="take_item" type="TakeItemOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="collect_items" type="CollectItemQuestOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="npc_use" type="ActionItemUseOperation" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="kill" type="KillOperation" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="override" type="xs:boolean" default="true"/>
	</xs:complexType>
	<xs:complexType name="DialogIdCondition">
		<xs:complexContent>
			<xs:extension base="QuestCondition">
				<xs:attribute name="value" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NpcIdCondition">
		<xs:complexContent>
			<xs:extension base="QuestCondition">
				<xs:attribute name="values" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PcInventoryCondition">
		<xs:complexContent>
			<xs:extension base="QuestCondition">
				<xs:attribute name="item_id" type="xs:int" use="required"/>
				<xs:attribute name="count" type="xs:long" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QuestStatusCondition">
		<xs:complexContent>
			<xs:extension base="QuestCondition">
				<xs:attribute name="value" type="QuestStatus" use="required"/>
				<xs:attribute name="quest_id" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QuestVarCondition">
		<xs:complexContent>
			<xs:extension base="QuestCondition">
				<xs:attribute name="value" type="xs:int" use="required"/>
				<xs:attribute name="var_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="GiveItemOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:attribute name="item_id" type="xs:int" use="required"/>
				<xs:attribute name="count" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SetQuestVarOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:attribute name="var_id" type="xs:int" use="required"/>
				<xs:attribute name="value" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NpcDialogOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:attribute name="id" type="xs:int" use="required"/>
				<xs:attribute name="quest_id" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SetQuestStatusOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:attribute name="status" type="QuestStatus" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="KillOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="StartQuestOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:attribute name="id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CollectItemQuestOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:sequence>
					<xs:element name="true" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
					<xs:element name="false" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
				<xs:attribute name="removeItems" type="xs:boolean" default="true"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ActionItemUseOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:sequence>
				  	<xs:element name="finish" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TakeItemOperation">
		<xs:complexContent>
			<xs:extension base="QuestOperation">
				<xs:attribute name="item_id" type="xs:int" use="required"/>
				<xs:attribute name="count" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="ConditionUnionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="AND"/>
			<xs:enumeration value="OR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ConditionOperation">
		<xs:restriction base="xs:string">
			<xs:enumeration value="EQUAL"/>
			<xs:enumeration value="GREATER"/>
			<xs:enumeration value="GREATER_EQUAL"/>
			<xs:enumeration value="LESSER"/>
			<xs:enumeration value="LESSER_EQUAL"/>
			<xs:enumeration value="NOT_EQUAL"/>
			<xs:enumeration value="IN"/>
			<xs:enumeration value="NOT_IN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="QuestStatus">
		<xs:restriction  base="xs:string">
			<xs:enumeration value="NONE"/>
			<xs:enumeration value="START"/>
			<xs:enumeration value="REWARD"/>
			<xs:enumeration value="COMPLETE"/>
			<xs:enumeration value="LOCKED"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ItemCollectingData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="next_npc_id" type="xs:int" default="0"/>
				<xs:attribute name="action_item_ids" type="IntListType" default="0"/>
				<xs:attribute name="end_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="0"/>
				<xs:attribute name="start_dialog_id2" type="xs:int" default="0"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="RelicRewardsData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="relic_var1" type="xs:int" use="required"/>
				<xs:attribute name="relic_var2" type="xs:int" use="required"/>
				<xs:attribute name="relic_var3" type="xs:int" use="required"/>
				<xs:attribute name="relic_var4" type="xs:int" use="required"/>
				<xs:attribute name="relic_count" type="xs:int" default="1"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CraftingRewardsData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="skill_id" type="xs:int" use="required"/>
				<xs:attribute name="level_reward" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ReportToData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="end_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="0"/>
                <xs:attribute name="start_dialog_id2" type="xs:int" default="0"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MonsterHuntData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="monster" type="Monster" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="end_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="0"/>
				<xs:attribute name="end_dialog_id" type="xs:int" default="0"/>
				<xs:attribute name="aggro_start_npcs" type="IntListType" default="0"/>
				<xs:attribute name="invasion_world" type="xs:int" default="0"/>
			    <xs:attribute name="reward" type="xs:boolean" default="false"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="MentorMonsterHuntData">
		<xs:complexContent>
			<xs:extension base="MonsterHuntData">
				<xs:attribute name="min_mente_level" type="xs:int" default="0"/>
				<xs:attribute name="max_mente_level" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="KillSpawnedData">
		<xs:complexContent>
			<xs:extension base="MonsterHuntData">
				<xs:sequence>
					<xs:element name="spawned_monster" type="SpawnedMonster" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ReportToManyData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="npc_infos" type="NpcInfos" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="start_item_id" type="xs:int" default="0"/>
				<xs:attribute name="start_dialog_id" type="xs:int" default="1011"/>
				<xs:attribute name="end_dialog_id" type="xs:int" default="2375"/>
				<xs:attribute name="end_npc_ids" type="IntListType" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="NpcInfos" >
		<xs:attribute name="var" type="xs:int" use="required"/>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="quest_dialog" type="xs:int" use="required"/>
		<xs:attribute name="close_dialog" type="xs:int" default="0"/>
		<xs:attribute name="movie" type="xs:int" default="0"/>
	</xs:complexType>
	<xs:complexType name="WorkOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="give_component" type="QuestItems" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="recipe_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Monster">
		<xs:attribute name="var" type="xs:int" use="required"/>
		<xs:attribute name="start_var" type="xs:int" default="0"/>
		<xs:attribute name="end_var" type="xs:int" use="required"/>
		<xs:attribute name="npc_ids" type="IntListType" use="required"/>
	</xs:complexType>
	<xs:complexType name="SpawnedMonster">
		<xs:complexContent>
			<xs:extension base="Monster">
				<xs:attribute name="spawner_object" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="KillInWorldData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" default="0"/>
				<xs:attribute name="end_npc_ids" type="IntListType" use="required"/>
				<xs:attribute name="worlds" type="IntListType" default="0"/>
				<xs:attribute name="amount" type="xs:int" use="required"/>
				<xs:attribute name="invasion_world" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ItemOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_item_id" type="xs:int" use="required"/>
				<xs:attribute name="talk_npc_id1" type="xs:int" default="0"/>
				<xs:attribute name="talk_npc_id2" type="xs:int" default="0"/>
				<xs:attribute name="end_npc_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="FountainRewardsData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_ids" type="IntListType" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SkillUseData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="skill" type="QuestSkillData" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="QuestSkillData">
		<xs:attribute name="ids" type="IntListType" use="required"/>
		<xs:attribute name="start_var" type="xs:int" default="0"/>
		<xs:attribute name="end_var" type="xs:int" use="required"/>
		<xs:attribute name="var_num" type="xs:int" default="0"/>
	</xs:complexType>
</xs:schema>

=== hnomkeng/AionEncomBase_Java8/AL-Game/data/static_data/quest_script_data/sanctum.xml
<?xml version="1.0" encoding="UTF-8"?>
<quest_scripts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quest_script_data.xsd">
<!--
    Quest Sanctum 5.1
	Make By (Encom)
 -->
	<report_to id="1950" start_npc_ids="203755" end_npc_ids="204424" item_id="182206023"/>
	<report_to id="1951" start_npc_ids="203788" end_npc_ids="278510" item_id="182206024"/>
	<report_to id="1952" start_npc_ids="203790" end_npc_ids="278511" item_id="182206025"/>
	<report_to id="1953" start_npc_ids="203792" end_npc_ids="278510" item_id="182206026"/>
	<report_to id="1954" start_npc_ids="203784" end_npc_ids="278507" item_id="182206027"/>
	<report_to id="1955" start_npc_ids="203786" end_npc_ids="278510" item_id="182206028"/>
	<report_to id="1956" start_npc_ids="203793" end_npc_ids="278511" item_id="182206029"/>
	<report_to id="3917" start_npc_ids="204656" end_npc_ids="804603"/>
	<report_to id="3960" start_npc_ids="798322" end_npc_ids="203711"/>
	<report_to id="3971" start_npc_ids="798386" end_npc_ids="203893" item_id="182206135"/>
	<report_to id="3974" start_npc_ids="798949" end_npc_ids="203893"/>
	<report_to id="3976" start_npc_ids="203723" end_npc_ids="798222" item_id="182206136"/>
	<report_to id="19040" start_npc_ids="203725" end_npc_ids="798440"/>
	<report_to id="19041" start_npc_ids="203711" end_npc_ids="798322"/>
	<report_to id="19044" start_npc_ids="798440" end_npc_ids="798438"/>
	<report_to id="19045" start_npc_ids="798438" end_npc_ids="798439"/>
	<report_to id="19065" start_npc_ids="203752" end_npc_ids="203701"/>
	
	<report_to_many id="3914" start_item_id="182206084" end_npc_ids="203384">
		<npc_infos npc_id="203752" var="0" quest_dialog="1352"/>
		<npc_infos npc_id="203384" var="1" quest_dialog="2375" close_dialog="1009"/>
	</report_to_many>
	
	<item_collecting id="1930" start_npc_ids="203767"/>
	<item_collecting id="1931" start_npc_ids="203837" action_item_ids="700230"/>
	<item_collecting id="1933" start_npc_ids="203833"/>
	<item_collecting id="1934" start_npc_ids="203833"/>
	<item_collecting id="3915" start_npc_ids="204656"/>
	<item_collecting id="3916" start_npc_ids="204656"/>
	<item_collecting id="3918" start_npc_ids="804603"/>
	<item_collecting id="3919" start_npc_ids="804603"/>
	<item_collecting id="3975" start_npc_ids="798321"/>
	<item_collecting id="19042" start_npc_ids="798322" end_npc_ids="798322"/>
	<item_collecting id="19043" start_npc_ids="798444"/>
	
	<monster_hunt id="1939" start_npc_ids="203703">
		<monster var="0" npc_ids="700265" end_var="3"/>
	</monster_hunt>
	<monster_hunt id="3978" start_npc_ids="798319">
		<monster var="0" npc_ids="215079" end_var="1"/>
	</monster_hunt>
	<monster_hunt id="3979" start_npc_ids="798322">
		<monster var="0" npc_ids="215081" end_var="1"/>
	</monster_hunt>
	
	<item_order start_item_id="182206034" end_npc_id="278555" id="1965"/>
	<item_order start_item_id="182206035" end_npc_id="278555" id="1966"/>
	<item_order start_item_id="182206036" end_npc_id="278555" id="1967"/>
	<item_order start_item_id="182206037" end_npc_id="278556" id="1968"/>
	<item_order start_item_id="182206038" end_npc_id="278556" id="1969"/>
	<item_order start_item_id="182206039" end_npc_id="278556" id="1970"/>
	
	<!-- CRAFT QUEST -->
	<!-- [Expert] Zest For Weaponsmithing -->
	<item_collecting id="3941" start_npc_ids="203788"/>
	<!-- [Expert] Weaponsmith's Craft -->
	<item_collecting id="3942" start_npc_ids="203788"/>
	<!-- [Expert] Expert Weaponsmith -->
	<report_to id="3943" start_npc_ids="203788" end_npc_ids="203700" item_id="182206102"/>
	<!-- [Expert] Zest For Armorsmithing -->
	<item_collecting id="3944" start_npc_ids="203790"/>
	<!-- [Expert] Armorsmith's Craft -->
	<item_collecting id="3945" start_npc_ids="203790"/>
	<!-- [Expert] Expert Armorsmith -->
	<report_to id="3946" start_npc_ids="203790" end_npc_ids="203700" item_id="182206103"/>
	<!-- [Expert] Zest For Handicrafting -->
	<item_collecting id="3947" start_npc_ids="203792"/>
	<!-- [Expert] Handicrafter's Craft -->
	<item_collecting id="3948" start_npc_ids="203792"/>
	<!-- [Expert] Expert Handicrafter -->
	<report_to id="3949" start_npc_ids="203792" end_npc_ids="203700" item_id="182206104"/>
	<!-- [Expert] Zest For Cooking -->
	<item_collecting id="3950" start_npc_ids="203784"/>
	<!-- [Expert] Cook's Craft -->
	<item_collecting id="3951" start_npc_ids="203784"/>
	<!-- [Expert] Expert Cook -->
	<report_to id="3952" start_npc_ids="203784" end_npc_ids="203700" item_id="182206105"/>
	<!-- [Expert] Zest For Alchemy -->
	<item_collecting id="3953" start_npc_ids="203786"/>
	<!-- [Expert] Alchemist's Craft -->
	<item_collecting id="3954" start_npc_ids="203786"/>
	<!-- [Expert] Expert Alchemist -->
	<report_to id="3955" start_npc_ids="203786" end_npc_ids="203700" item_id="182206106"/>
	<!-- [Expert] Zest For Tailoring -->
	<item_collecting id="3956" start_npc_ids="203793"/>
	<!-- [Expert] Tailor's Craft -->
	<item_collecting id="3957" start_npc_ids="203793"/>
	<!-- [Expert] Expert Tailor -->
	<report_to id="3958" start_npc_ids="203793" end_npc_ids="203700" item_id="182206107"/>
	<!-- [Expert] Constructor's Test -->
	<item_collecting id="19052" start_npc_ids="798450"/>
	<!-- [Expert] Expert Of Construction -->
	<item_collecting id="19053" start_npc_ids="798450"/>
	<!-- [Expert] Requirements For Construction Expert -->
	<item_collecting id="19055" start_npc_ids="798450"/>
	<!-- [Expert] Construction Expert -->
	<report_to id="19056" start_npc_ids="798450" end_npc_ids="203700" item_id="182212226"/>
	
	<!-- SKILL USE QUEST -->
	<!-- Meaning Of Life -->
	<skill_use id="3910" start_npc_id="203707">
		<skill end_var="100" ids="9912"/>
	</skill_use>
	<!-- Intention Of Lady Yustiel -->
	<skill_use id="3912" start_npc_id="203707">
		<skill end_var="20" ids="890 1100 1699 4646 4004"/>
	</skill_use>
	<!-- The Gladiator Preceptor's Task -->
	<skill_use id="3922" start_npc_id="203704">
		<skill end_var="10" ids="599"/>
	</skill_use>
	<!-- The Templar Preceptor's Task -->
	<skill_use id="3923" start_npc_id="203704">
		<skill end_var="10" ids="3161"/>
	</skill_use>
	<!-- The Ranger Preceptor's Task -->
	<skill_use id="3924" start_npc_id="203705">
		<skill end_var="10" ids="4610"/>
	</skill_use>
	<!-- The Assassin Preceptor's Task -->
	<skill_use id="3925" start_npc_id="203705">
		<skill end_var="10" ids="3491"/>
	</skill_use>
	<!-- The Sorcerer Preceptor's Task -->
	<skill_use id="3926" start_npc_id="203706">
		<skill end_var="10" ids="1338"/>
	</skill_use>
	<!-- The Spiritmaster Preceptor's Task -->
	<skill_use id="3927" start_npc_id="203706">
		<skill end_var="10" ids="3781"/>
	</skill_use>
	<!-- The Cleric Preceptor's Task -->
	<skill_use id="3928" start_npc_id="203707">
		<skill end_var="10" ids="4220"/>
	</skill_use>
	<!-- The Chanter Preceptor's Task -->
	<skill_use id="3929" start_npc_id="203707">
		<skill end_var="10" ids="1810"/>
	</skill_use>
	<!-- The Gunslinger Preceptors Task -->
	<skill_use id="19074" start_npc_id="801214">
		<skill end_var="10" ids="2007"/>
	</skill_use>
	<!-- The Songweaver Preceptors Task -->
	<skill_use id="19075" start_npc_id="801215">
		<skill end_var="10" ids="4469"/>
	</skill_use>
	<!-- Master Aethertech -->
	<skill_use id="19078" start_npc_id="801214">
		<skill end_var="10" ids="2572"/>
	</skill_use>
</quest_scripts>
